# Generated by Django 3.2.7 on 2021-12-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('hilt', models.TextField(max_length=250)),
                ('blades', models.IntegerField()),
            ],
        ),
    ]
