# Generated by Django 3.2.7 on 2022-01-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_repairing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crystal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='repairing',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='repairing',
            name='date',
            field=models.DateField(verbose_name='Repair Date'),
        ),
    ]
