# Generated by Django 3.2.7 on 2022-01-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20220101_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='saber',
            name='crystals',
            field=models.ManyToManyField(to='main_app.Crystal'),
        ),
    ]
